### ISSUE TITLE
(Self-Voicing) Design Issues from Interviews

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#191]
Several design issues are emerging from interviews. I am going to start listing them out here so they don't get lost.
Checked ones are resolved or have their own issue:
- [x] Grab buttons don't have voicing names, see #190 
- [x] Overview needs some indication of the zoomed-in view. Some explanation of how the books and zoomed-in view are related, but without getting technical and keeping things  "fun". #195 
- [x] Overview wording after a "breakaway" seems to have some kind of mistake in it. I hear "dot". #196 
- [x] Hints - need lots of subtle changes to the hints - order and timing both need improvement. @Matthew-Moore240, my guess is that if you better understand how the hints were used in the interactive description design, you'll be able to see how best to use them in the Voicing design. #194 
- [x] The break away response has to be heard, @jessegreenberg, is it possible to make it assertive? (#192)

**Comment by Matthew-Moore240** [comment]
Made issues for all three of the unchecked boxes.

**Comment by terracoda** [comment]
These issues will be tracked in their own issues, so closing this issue.
