### ISSUE TITLE
PhET-iO Instrumentation checklist

### ISSUE THREAD

**Issue by samreid** [phetsims/friction#67]
From #64 

### Before instrumenting
 - [x] Copy this checklist to the issue description (top issue comment) for tracking. Link back to this checklist via `/blob/<SHA>/` so that the specific guide you used is preserved. https://github.com/phetsims/phet-io/blob/b6303f013f9571158fe46a9e4b98b1382f35dd91/doc/how-to-instrument-a-phet-simulation-for-phet-io.md
 - [x] [Understand the goal](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#understand-the-goal)
 - [x] Create a dev release before beginning. This creates a benchmark to reference against for memory-leaks, sim size, performance, etc.
 - [x] [Review the Code](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#review-the-code)
 - [x] [Keep tips and tricks in mind as you instrument](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#tips-tricks-notes-misc)
 - [x] Have a PhET-iO design meeting for the simulation to identify what should be customizable/interoperable/data stream.  For example, see how-to-design-phet-io-features-for-a-simulation.md
 
 ### The instrumentation Process
 - [x] [Import Tandem to main.js](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#import-tandem-to-mainjs)
 - [x] [Create root tandem](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#create-root-tandem)
 - [x] [Pass tandems to sim screens](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-sim-screens)
 - [x] [Pass tandems to model and view](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-model-and-view)
  - [x] Add 'phet-io' as a supportedBrand in the sim's package.json, then run `grunt generate-data` in perennial (and check in changes under perennial/data), then you can use phetmarks to load wrappers for testing.
 - [x] [Pass tandems to all constructors defined by the simulation](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-all-constructors-defined-by-the-simulation)
   + See also [Testing while adding Tandem instances](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#testing-while-adding-tandem-instances). Test with `?phetioValidateTandems=false` since some common code-components don't yet have tandems.
 - [x] [Pass tandem instances to common code components](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandem-instances-to-common-code-components)
   + See also [Testing while adding Tandem instances](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#testing-while-adding-tandem-instances).
 - [x] [Create static tandems where appropriate](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#create-static-tandems-where-appropriate).
 - [x] [Instrument any uninstrumented common-code components used by the sim](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#instrument-any-uninstrumented-common-code-components-used-by-the-sim)
 - [x] [Instrument new component types defined by the sim](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#instrument-new-component-types-defined-by-the-sim)
 - [x] [IO Types should use proper inheritance](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#io-types-should-use-proper-inheritance)
 - [x] [Add simulation specific support](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#add-simulation-specific-support)
 - [x] [Support dynamic state](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#support-dynamic-state)
 - [x] [Test for memory leaks](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#test-for-memory-leaks)
 
 ### After instrumenting
 - [x] Make sure Joist `dt` values are used instead of Date.now() or other Date functions.  This is necessary for reproducible playback via input events.
 - [x] Are random numbers using `phet.joist.random`, and all doing so after modules are declared (non-statically)?  For example, the following methods (and perhaps others) should not be used: `Math.random`, `_.shuffle`, `_.sample`, `_.random`.
 - [x] `undefined` values cannot be saved by phet-io, sims should be written to use `null` instead.
 - [x] Verify that the simulation works in all of the phet-io wrappers.
 - [x] Build with `grunt --brand=phet-io` and test the built version by launching build/wrappers/index and testing all the links.
 - [x] Manually look through Instance Proxies to make sure that tandems work as expected and are formatted correctly.
 - [x] Perform a full test for memory leaks. The benchmark dev release can be helpful here. This will help catch faulty tandem disposal.
 - [x] If the instrumentation process was large enough, then there is reason for another code review (or partial). Use your judgement. Ask @ariel-phet or @kathy-phet if you are worried about the cost. 
 - [x] Set up a task to have the newly instrumented sim dev tested by the QA team. 
 - [x] Update these instructions if you find them to be incomplete, inconsistent or incorrect.
 - [x] After publishing, add your instrumented simulation to the spreadsheet here: https://docs.google.com/spreadsheets/d/1pU9izdNQkd9vr8TvLAfXe_v68yh-7potH-y712FBPr8/edit#gid=0
 - [x] [In conclusion](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#in-conclusion)

**Comment by samreid** [comment]
Everything complete or moved to new issues, closing.
